Update deployment.yml

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -73,15 +73,13 @@ jobs:
         cd Kubernetes/Policy
         POLICY_NAME="AWSLoadBalancerControllerIAMPolicy"
         POLICY_ARN=$(aws iam list-policies --query "Policies[?PolicyName=='${POLICY_NAME}'].Arn" --output text)
-        
-        if [ "$POLICY_ARN" == "None" ]; then
-          echo "Creating IAM policy..."
-          aws iam create-policy \
-            --policy-name ${POLICY_NAME} \
-            --policy-document file://alb_controller_iam_policy.json
-        else
-          echo "IAM policy '${POLICY_NAME}' already exists with ARN: ${POLICY_ARN}"
-        fi
+        eksctl create iamserviceaccount \
+          --cluster=EKS-Development \
+          --namespace=kube-system \
+          --name=aws-load-balancer-controller \
+          --attach-policy-arn=arn:aws:iam::381491938951:policy/AWSLoadBalancerControllerIAMPolicy \
+          --approve \
+          --override-existing-serviceaccounts
 
     - name: Create IAM service account
       run: |
@@ -103,28 +101,6 @@ jobs:
       run: |
         VPC_ID=$(aws eks describe-cluster --name EKS-Development --query "cluster.resourcesVpcConfig.vpcId" --output text)
         echo "::set-output name=vpc_id::$VPC_ID"
-    
-    - name: Check if Helm release exists
-      id: helm_check
-      run: |
-        if helm list -n kube-system | grep -q "aws-load-balancer-controller"; then
-          echo "Helm release 'aws-load-balancer-controller' already exists."
-          echo "EXISTS=true" >> $GITHUB_ENV
-        else
-          echo "Helm release 'aws-load-balancer-controller' does not exist."
-          echo "EXISTS=false" >> $GITHUB_ENV
-        fi
-    
-    - name: Check for existing AWS Load Balancer
-      id: check_load_balancer
-      run: |
-        if kubectl get svc -A -o=jsonpath='{.items[?(@.spec.type=="LoadBalancer")].metadata.name}' | grep -q '.'; then
-          echo "LoadBalancer service already exists."
-          echo "LOAD_BALANCER_EXISTS=true" >> $GITHUB_ENV
-        else
-          echo "No LoadBalancer service found."
-          echo "LOAD_BALANCER_EXISTS=false" >> $GITHUB_ENV
-        fi
     
     - name: Install or Upgrade AWS Load Balancer Controller
       run: |
@@ -150,10 +126,17 @@ jobs:
     
     - name: Wait for AWS Load Balancer Controller
       run: |
-        while ! kubectl get deployment aws-load-balancer-controller -n kube-system > /dev/null 2>&1; do
-          echo "Waiting for AWS Load Balancer Controller deployment to be available..."
-          sleep 30
+        for i in {1..10}; do
+          if kubectl get deployment aws-load-balancer-controller -n kube-system | grep -q '2/2'; then
+            echo "AWS Load Balancer Controller is available."
+            exit 0
+          else
+            echo "Waiting for AWS Load Balancer Controller deployment to be available..."
+            sleep 30
+          fi
         done
+        echo "AWS Load Balancer Controller failed to become available."
+        exit 1
     
     - name: Verify AWS Load Balancer Controller Deployment
       run: |
