Update deployment.yml

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -104,7 +104,7 @@ jobs:
     
     - name: Install or Upgrade AWS Load Balancer Controller
       run: |
-        if [ "${{ env.EXISTS }}" == "true" ]; then
+        if helm list -n kube-system | grep -q "aws-load-balancer-controller"; then
           echo "Upgrading existing AWS Load Balancer Controller..."
           helm upgrade aws-load-balancer-controller eks/aws-load-balancer-controller \
             -n kube-system \
@@ -123,20 +123,25 @@ jobs:
             --set vpcId=${{ steps.vpc.outputs.vpc_id }} \
             --set serviceAccount.name=aws-load-balancer-controller
         fi
-    
+
     - name: Wait for AWS Load Balancer Controller
       run: |
-        for i in {1..10}; do
+        timeout=60
+        start_time=$(date +%s)
+        while true; do
+          current_time=$(date +%s)
+          elapsed_time=$((current_time - start_time))
           if kubectl get deployment aws-load-balancer-controller -n kube-system | grep -q '2/2'; then
-            echo "AWS Load Balancer Controller is available."
+            echo "AWS Load Balancer Controller deployment is available."
             exit 0
+          elif [ $elapsed_time -ge $timeout ]; then
+            echo "AWS Load Balancer Controller failed to become available within timeout period."
+            exit 1
           else
             echo "Waiting for AWS Load Balancer Controller deployment to be available..."
             sleep 30
           fi
         done
-        echo "AWS Load Balancer Controller failed to become available."
-        exit 1
     
     - name: Verify AWS Load Balancer Controller Deployment
       run: |
